pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('Exp-4-Jenkins-CI-Pipeline') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Exp-4-Jenkins-CI-Pipeline') {
                    sh 'mvn test'
                }
            }
        }

    }

    post {
        success {
            echo 'CI Pipeline Executed Successfully!'
        }

        failure {
            echo 'CI Pipeline Failed!'
        }
    }
}
