pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

    }

    post {
        success {
            echo 'CI Pipeline Executed Successfully!'
        }
        failure {
            echo 'CI Pipeline Failed!'
        }
    }
}
